Associations and queries
SimbaWANGU/blog-app pull request #2
Opened 2022-08-09 14:49 UTC by SimbaWANGU

In this Pull Request, the following list of requirements were completed:
1. Created models
2. Used models to insert data using `rails c` command
3. Created the following custom methods:
    - A method that returns the 3 most recent posts for a given user.
    - A method that updates the posts counter for a user.
    - A method which returns the 5 most recent comments for a given post.
    - A method that updates the comments counter for a post.
    - A method that updates the likes counter for a post.

2022-08-09 16:13 UTC, mmsesay requested changes
Hi @SimbaWANGU, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
 - Good Readme :heavy_check_mark: 
 - No linter error :heavy_check_mark: 
 - Good PR title & summary :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-10 08:39 UTC, SimbaWANGU commented on app/models/author.rb
> +  end
Thank you very much for this illustration @mmsesay 👍

2022-08-10 08:45 UTC, elmar8287 approved these changes
Hi, @SimbaWANGU.

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

### Highlights

- You have implemented all suggestions from the previous reviewer 👍 

### Optional suggestions

- Please, consider fixing the broken link to the MIT.md file 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
### Please, remember to tag me (@elmar8287) in your question so I can receive the notification 👍 
![giphy](https://user-images.githubusercontent.com/49064106/180751457-52107e57-31fd-486c-97fe-bcccf4e449af.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-10 08:53 UTC, SimbaWANGU commented
@elmar8287 thank you for the review 👍

2022-08-10 08:53 UTC, merged