Rails forms
SimbaWANGU/blog-app pull request #9
Opened 2022-08-24 16:42 UTC by SimbaWANGU

The following changes were introduced in this Pull Request:
- Create a method called current_user in your ApplicationController to make current user data available to all controllers.
    - It will return the first user from the database.
    - Don't worry about proper authentication at this time. You will add it in the upcoming projects.
- Create forms to perform the following functions:
    - Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).
    - Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).
- Allow Users to add likes to Posts.

2022-08-24 17:57 UTC, codepantha requested changes
# STATUS: REQUIRES CHANGES ♻️ 

## Hi @SimbaWANGU 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/is14HLE2EUHPryPkmU/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Used GitFlow
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 17:57 UTC, codepantha commented on app/controllers/posts_controller.rb
> +  end
- [ ] Kindly create a Comments Controller. Any CRUD operation that has to do with the comments should happen in the Comments controller and not here. Therefore, this method should be extracted and put in there.
- [ ] In the Comments controller which you will create, please create a `comments#new` action which will render a form in the `views/comments/new.html.erb` file which accepts input for creating comments.

2022-08-24 17:57 UTC, codepantha commented on app/views/posts/index.html.erb
> +  <% end %>
- [ ] `GET /posts/new` should render a `views/posts/new.html.erb` file which has a form that accepts inputs to create a new post. Currently, when I visit the `GET /posts/new` route, an error occurs because that file doesn't exist. Please create it, and move this form there 🙏 
![image](https://user-images.githubusercontent.com/46839548/186487131-807f79c2-da19-44aa-a5b0-3e3f7a679b1a.png)

2022-08-24 17:57 UTC, codepantha commented on config/routes.rb
> +post '/addlike/:id', to: "posts#add_like"
- [ ] In the routes you have above, you are pointing to the `add_comment` and `add_like` actions which you have created in your `posts_controller`. However, as I suggested earlier each of those actions should be in the `Comments Controller` and `Likes controller` respectively. Having said that, there is a need to rewrite your routes to effect this change 👍

2022-08-24 17:57 UTC, codepantha commented on app/controllers/posts_controller.rb
> +    end
- [ ] Kindly create a Likes Controller. Any CRUD operation that has to do with the comments should happen in the Likes controller and not here. Therefore, this method should be extracted and put in there.

2022-08-25 10:17 UTC, Davidosky007 approved these changes
Hi @SimbaWANGU 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Good looking readme file 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 10:37 UTC, merged